[package]
name = "permissive-selinux"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[dependencies]

[build-dependencies]

[package.metadata.build-package]