schema-version = 1
release-version = "1.0.3-kernalkit-5.3.2-corekit-14.0.0-sdk-0.72.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "5.3.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "14.0.0"
vendor = "bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.72.0"
vendor = "bottlerocket"
