schema-version = 1
release-version = "0.0.2"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.62.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "9.1.0"
vendor = "bottlerocket"