schema-version = 1
release-version = "0.0.3"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.63.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "10.1.2"
vendor = "bottlerocket"
