schema-version = 1
release-version = "1.0.5"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "7.2.1"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "15.0.0"
vendor = "bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.77.0"
vendor = "bottlerocket"
