[package]
name = "jsoncpp"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/open-source-parsers/jsoncpp/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/1.9.6.tar.gz"
sha512 = "006d81f9f723dcfe875ebc2147449c07c5246bf97dd7b9eee1909decc914b051d6f3f06feb5c3dfa143d28773fb310aabb04a81dc447cc61513309df8eba8b08"

[dependencies]
